name: Maven CI/CD

on:
  push:
    branches:
      - main # Cambia esto a tu rama por defecto
  pull_request:
    branches:
      - main

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
  #  orders-service
      - name: Run tests for orders-service
        working-directory: orders-service-example
        run: mvn -B test --file pom.xml 

      - name: Build orders-service
        working-directory: orders-service-example
        run: mvn -B package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: orders-service
          path: orders-service-example/target/*.jar 
          
  # payments-service   
      - name: Run tests for payments-service
        working-directory: payments-service-example
        run: mvn -B test --file pom.xml
  
      - name: Build payments-service
        working-directory: payments-service-example
        run: mvn -B package --file pom.xml

      - name: Upload payments JAR file
        uses: actions/upload-artifact@v4
        with:
          name: payments-service
          path: payments-service-example/target/*.jar

  # products-service     
      - name: Run tests for products-service
        working-directory: products-service-example
        run: mvn -B test --file pom.xml  

      - name: Build products-service
        working-directory: products-service-example
        run: mvn -B package --file pom.xml

      - name: Upload products JAR file
        uses: actions/upload-artifact@v4
        with:
            name: products-service
            path: products-service-example/target/*.jar 

  #shipping-service
      - name: Run tests for shipping-service
        working-directory: shipping-service-example
        run: mvn -B test --file pom.xml

      - name: Build shipping-service
        working-directory: shipping-service-example
        run: mvn -B package --file pom.xml

      - name: Upload shipping JAR file
        uses: actions/upload-artifact@v4
        with:
              name: shipping-service
              path: shipping-service-example/target/*.jar
