name: Maven CI/CD

on:
  push:
    branches:
      - main # Cambia esto a tu rama por defecto
  pull_request:
    branches:
      - main

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build orders-service
        working-directory: orders-service-example
        run: mvn -B package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: orders-service
          path: orders-service-example/target/*.jar # Cambia esto si tu archivo JAR tiene un nombre específico
      
      - name: Build payments-service
        working-directory: payments-service-example
        run: mvn -B package --file pom.xml

      - name: Upload payments JAR file
        uses: actions/upload-artifact@v4
        with:
          name: payments-service
          path: payments-service-example/target/*.jar 
