name: Maven CI/CD

on:
  push:
    branches:
      - main # Change this to your default branch
  pull_request:
    branches:
      - main

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      working-directory: orders-service-example
      run: mvn -B package --file pom.xml

    - name: Upload JAR file
      working-directory: orders-service-example
      uses: actions/upload-artifact@v2
      with:
          name: my-app-jar
          path: target/*.jar # Cambia esto si tu archivo JAR tiene un nombre específico
