name: Maven CI/CD

on:
  push:
    branches:
      - main # Cambia esto a tu rama por defecto
  pull_request:
    branches:
      - main

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build orders-service
        working-directory: orders-service-example
        run: mvn -B package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: my-app-jar
          path: orders-service-example/target/*.jar # Cambia esto si tu archivo JAR tiene un nombre específico
      
      - name: Build payments-service
        working-directory: payments-service-example
        run: mvn -B package --file pom.xml

      - name: Upload payments JAR file
        uses: actions/upload-artifact@v3
        with:
          name: my-app-jar
          path: payments-service-example/target/*.jar 
